"""exam all_items

Revision ID: 4334840c8344
Revises: d64aa643ffff
Create Date: 2026-10-08 16:27:50.547189

"""
from alembic import op
import sqlalchemy as sa


revision = '4334840c8344'
down_revision = 'd64aa643ffff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('all_items', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('all_items')

    # ### end Alembic commands ###
