"""uploads in database, processing steps

Revision ID: d64aa643ffff
Revises: 8cd2d3f4a388
Create Date: 2026-10-08 10:14:08.111463

"""
from alembic import op
import sqlalchemy as sa


revision = 'd64aa643ffff'
down_revision = '8cd2d3f4a388'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=8), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_files',
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('upload_chunks',
    sa.Column('upload_id', sa.String(length=32), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('upload_id', 'index')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('step_started_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step_started_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('step_started_at')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('step_started_at')
        batch_op.drop_column('size')

    op.drop_table('upload_chunks')
    op.drop_table('document_files')
    op.drop_table('upload_sessions')
    # ### end Alembic commands ###
